import { Course, SiteSettings, FAQItem, TestimonialItem } from './types';

export const initialSiteSettings: SiteSettings = {
  siteTitle: 'বিডি হোমিও প্রশিক্ষণ কেন্দ্র',
  slogan: 'Right Homeopath, Right Homeopathy',
  heroHeadline: 'হোমিওপ্যাথির খাঁটি দর্শনে আত্মবিশ্বাসী প্র্যাকটিশনার হওয়ার ৬ মাসের মাস্টার একাডেমি',
  heroSubheadline: 'ডাঃ মোঃ গিয়াস উদ্দিন স্যারের সরাসরি নির্দেশনায় অর্গানন অব মেডিসিন, মেটেরিয়া মেডিকা ও রেপার্টরি ভিত্তিক সপ্তাহে ২টি লাইভ ক্লাস ও ৬ দিন মর্নিং কেস সাপোর্ট।',
  doctorName: 'ডাঃ মোঃ গিয়াস উদ্দিন',
  doctorTitle: 'প্রতিষ্ঠাতা ও প্রধান প্রশিক্ষক, বিডি হোমিও',
  doctorMessage: 'অর্গাননের সঠিক জ্ঞান ছাড়া লক্ষণ ভিত্তিক হোমিওপ্যাথি চিকিৎসা অসম্ভব। আমাদের লক্ষ্য— প্রতিটি শিক্ষার্থী যেন কেবল তাত্ত্বিক জ্ঞান নয়, বরং চেম্বারে রোগী আরোগ্যের পূর্ণ আত্মবিশ্বাস নিয়ে চিকিৎসা সেবা প্রদান করতে পারেন।',
  heroImageUrl: '/assets/sir/sir-hero.jpg',
  doctorPortraitUrl: '/assets/sir/sir-portrait.jpg',
  ptfCertificateImageUrl: '/assets/gallery/certificate-ptf-1.jpg',
  galleryImages: [
    {
      id: 'g1',
      src: '/assets/gallery/certificate-ptf-1.jpg',
      title: 'কৃতি শিক্ষার্থীদের PTF সার্টিফিকেট বিতরণী',
      category: 'সার্টিফিকেশন',
      desc: 'কোর্স সমাপনী ব্যাচের শিক্ষার্থীদের সম্মাননা ও সনদ প্রদান',
    },
    {
      id: 'g2',
      src: '/assets/gallery/workshop-practical.jpg',
      title: 'হোমিওপ্যাথিক কেস স্টাডি ও বাস্তব কর্মশালা',
      category: 'কর্মশালা',
      desc: 'ডাঃ মোঃ গিয়াস উদ্দিন স্যারের সরাসরি ক্লিনিক্যাল ক্লাস',
    },
    {
      id: 'g3',
      src: '/assets/gallery/seminar-session.jpg',
      title: 'চিকিৎসকদের সাথে মতবিনিময় ও গ্রুপ স্টাডি',
      category: 'আলোচনা সভা',
      desc: 'বিভিন্ন জেলা থেকে আগত চিকিৎসকদের মতবিনিময় ও অভিজ্ঞতা শেয়ার',
    },
    {
      id: 'g4',
      src: '/assets/gallery/clinical-books.jpg',
      title: 'হ্যানিম্যানের মূলগ্রন্থ ও রেপার্টরি গবেষণা',
      category: 'একাডেমিক সেশন',
      desc: 'ক্লাসিক্যাল নীতিমালার প্র্যাকটিক্যাল ব্যবহার',
    },
  ],
  bkashNumber: '01815-883101',
  bkashType: 'Merchant',
  nagadNumber: '01815-883101',
  nagadType: 'Personal',
  whatsappNumber: '01811-123993',
  helplineNumber: '01811-123993',
  classTime: 'রাত ৯:৩০ টা',
  googleMeetUrl: 'https://meet.google.com/bdhomeo-live-class',
  noticeText: 'আগামী নতুন ব্যাচের ভর্তি চলছে! ফ্রি ওরিয়েন্টেশন ক্লাসে অংশ নিতে এখনই রেজিস্ট্রেশন করুন। হেল্পলাইন: 01811-123993',
  youtubeUrl: 'https://www.youtube.com/@bdhomeo/videos',
  facebookUrl: 'https://www.facebook.com/geaus.uddin.81099',
};

export const initialCourses: Course[] = [
  {
    id: 'course-basic-foundation',
    slug: 'basic-homeopathy-foundation',
    title: 'বেসিক হোমিওপ্যাথি ফাউন্ডেশন কোর্স',
    subtitle: 'হ্যানিম্যানের অর্গানন, মেটেরিয়া মেডিকা ও রেপার্টরি পরিচিতির ৬ মাসের পূর্ণাঙ্গ একাডেমিক কোর্স',
    batchType: 'basic',
    durationMonths: 6,
    admissionFee: 1000,
    monthlyFee: 500,
    liveSchedule: 'সপ্তাহে ২ দিন লাইভ ক্লাস (রাত ৯:৩০)',
    thumbnailUrl: '/assets/courses/basic-batch.jpg',
    description: 'যারা নতুনভাবে অর্গানন ও মেটেরিয়া মেডিকার সঠিক জ্ঞান অর্জন করে প্র্যাকটিসে নামতে চান, তাদের জন্য এই ৬ মাসের কোর্স। প্রতিটি ওষুধের মূল সুর, লক্ষণ সংগ্রহ ও প্রেসক্রিপশন তৈরির মূলনীতি শেখানো হয়।',
    features: [
      'সাপ্তাহিক ২টি লাইভ ক্লাস (Google Meet)',
      'অধ্যায়ভিত্তিক সাজানো PDF লেকচার শিট',
      'ফুল HD রেকর্ডেড ক্লাস লাইব্রেরি আনলক',
      'PTF অনুমোদিত প্রফেশনাল সার্টিফিকেট',
      'কোর্স শেষে কুরিয়ারে সার্টিফিকেট হোম ডেলিভারি',
    ],
    curriculum: [
      {
        id: 'c1',
        chapterNo: 1,
        title: 'অর্গানন অব মেডিসিন — মৌলিক ভিত্তি ও দর্শন',
        description: 'স্যামুয়েল হ্যানিম্যানের মূল এফোরিজম ও হোমিওপ্যাথিক নীতিমালার গভীর বিশ্লেষণ',
        lessons: [
          {
            id: 'l1',
            title: '১.১ হোমিওপ্যাথির ইতিহাস ও হ্যানিম্যানের অবিচল দর্শন (ফ্রি ওরিয়েন্টেশন ক্লাস)',
            durationMin: 45,
            isFreePreview: true,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Chapter-1-Organon-Basics.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf1/view',
          },
          {
            id: 'l2',
            title: '১.২ ভাইটাল ফোর্স (Vital Force) ও রোগ সৃষ্টির অন্তর্নিহিত কারণ',
            durationMin: 55,
            isFreePreview: true,
            youtubeVideoId: 'LXb3EKWsInQ',
            pdfNotesTitle: 'Chapter-1-Vital-Force.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf2/view',
          },
          {
            id: 'l3',
            title: '১.৩ মায়াজম তত্ত্ব — সোরিক, সাইকোটিক ও সিফিলিটিক মূল্যায়ন',
            durationMin: 60,
            isFreePreview: false,
            youtubeVideoId: 'fJ9rUzIMcZQ',
            pdfNotesTitle: 'Chapter-1-Miasm-Theory.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf3/view',
          },
        ],
      },
      {
        id: 'c2',
        chapterNo: 2,
        title: 'ক্লিনিক্যাল মেটেরিয়া মেডিকা — পলিক্রেস্ট ড্রাগ স্টাডি',
        description: 'রোগীর মানসিক লক্ষণ ও শারীরিক লক্ষণের সংযোগে ওষুধ নির্বাচন',
        lessons: [
          {
            id: 'l4',
            title: '২.১ সালফার (Sulphur) এর গভীর মনোদৈহিক চিত্র ও ড্রাগ পিকচার',
            durationMin: 50,
            isFreePreview: true,
            youtubeVideoId: '3JZ_D3ELwOQ',
            pdfNotesTitle: 'Chapter-2-Sulphur-Study.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf4/view',
          },
          {
            id: 'l5',
            title: '২.২ নাক্স ভমিকা (Nux Vomica) ও লাইকোপোডিয়ামের তুলনামূলক বিচার',
            durationMin: 65,
            isFreePreview: false,
            youtubeVideoId: 'LXb3EKWsInQ',
            pdfNotesTitle: 'Chapter-2-Nux-Lyc-Comparison.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf5/view',
          },
          {
            id: 'l6',
            title: '২.৩ পালসেটিলা ও আর্সেনিক অ্যালবামের ক্লিনিক্যাল ব্যবহার',
            durationMin: 55,
            isFreePreview: false,
            youtubeVideoId: 'fJ9rUzIMcZQ',
            pdfNotesTitle: 'Chapter-2-Puls-Ars-Clinical.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf6/view',
          },
        ],
      },
      {
        id: 'c3',
        chapterNo: 3,
        title: 'কেস টেকিং ও লক্ষণ সংগ্রহ পদ্ধতি',
        description: 'চেম্বারে রোগীর কথা শোনা, লক্ষণ নথিভুক্তকরণ ও রুব্রিক্স তৈরি',
        lessons: [
          {
            id: 'l7',
            title: '৩.১ হ্যানিম্যানিয়ান কেস টেকিং শিট তৈরি ও রোগী পর্যবেক্ষণের কৌশল',
            durationMin: 50,
            isFreePreview: false,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Chapter-3-Case-Taking-Sheet.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf7/view',
          },
          {
            id: 'l8',
            title: '৩.২ পোটেন্সি ও ডোজ সিলেকশন — ৫০ সহস্রতমিক ও শততমিক পদ্ধতি',
            durationMin: 45,
            isFreePreview: false,
            youtubeVideoId: '3JZ_D3ELwOQ',
            pdfNotesTitle: 'Chapter-3-Potency-Dose.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf8/view',
          },
        ],
      },
    ],
  },
  {
    id: 'course-advance-mastery',
    slug: 'advance-clinical-repertory',
    title: 'এডভান্সড ক্লিনিক্যাল রেপার্টরি ও কেস ম্যানেজমেন্ট',
    subtitle: 'জটিল ও ক্রনিক রোগের সমাধান, রেপার্টরাইজেশন এবং সপ্তাহে ৬ দিন সকালের বিশেষ মর্নিং কেস সাপোর্ট',
    batchType: 'advance',
    durationMonths: 6,
    admissionFee: 1000,
    monthlyFee: 500,
    liveSchedule: 'সাপ্তাহিক ২টি লাইভ ক্লাস (রাত ৯:৩০)',
    morningSupport: 'সপ্তাহে ৬ দিন সকাল ৮:০০ টায় মর্নিং কেস সাপোর্ট',
    thumbnailUrl: '/assets/courses/advance-batch.jpg',
    description: 'চলমান চিকিৎসক ও প্র্যাকটিশনারদের জন্য একটি অনন্য কোর্স। কেনটের রেপার্টরি ও সিন্থেসিস সফটওয়্যার ব্যবহারের পাশাপাশি প্রতিদিন সকাল ৮:০০ টায় সরাসরি স্যারের সাথে জটিল কেস নিয়ে আলোচনা করে প্রেসক্রিপশন চূড়ান্ত করা যায়।',
    features: [
      'সাপ্তাহিক ২টি মূল লাইভ ক্লাস (Google Meet)',
      'সপ্তাহে ৬ দিন সকাল ৮:০০ টায় লাইভ মর্নিং কেস সাপোর্ট',
      'জটিল কেসের রুব্রিক্স সিলেকশন ও সফটওয়্যার রেপার্টরাইজেশন',
      'ইনফার্টিলিটি, টিউমার ও ক্রনিক রোগের বিশেষ প্রোটোকল',
      'অধ্যায়ভিত্তিক রিচ PDF নোট ও আনলিস্টেড ভিডিও লাইব্রেরি',
      'PTF অনুমোদিত সার্টিফিকেট ও কুরিয়ার হোম ডেলিভারি',
    ],
    curriculum: [
      {
        id: 'adv-c1',
        chapterNo: 1,
        title: 'রেপার্টরি মাস্টারি ও রুব্রিক্স ডিকোড',
        description: 'কেনট ও বোগার রেপার্টরির গভীর অধ্যায়ন ও রুব্রিক্সের ক্লিনিক্যাল অর্থ',
        lessons: [
          {
            id: 'adv-l1',
            title: '১.১ রেপার্টরি ব্যবহারের সঠিক নিয়ম — ৩/৪ মাসে পারদর্শী হওয়ার গাইডলাইন',
            durationMin: 60,
            isFreePreview: true,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Adv-Chapter-1-Repertory-Guide.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf9/view',
          },
          {
            id: 'adv-l2',
            title: '১.২ মানসিক রুব্রিক্স নির্বাচন ও রোগীর লুকায়িত মনের ভাব বোঝা',
            durationMin: 70,
            isFreePreview: true,
            youtubeVideoId: 'LXb3EKWsInQ',
            pdfNotesTitle: 'Adv-Chapter-1-Mind-Rubrics.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf10/view',
          },
        ],
      },
      {
        id: 'adv-c2',
        chapterNo: 2,
        title: 'স্পেশাল প্যাথোলজি — গাইনি ও ইনফার্টিলিটি কেস স্টাডি',
        description: 'বন্ধ্যাত্ব, ওভারিয়ান সিস্ট ও জরায়ু টিউমারের সফল চিকিৎসা পদ্ধতি',
        lessons: [
          {
            id: 'adv-l3',
            title: '২.১ ফিমেল ইনফার্টিলিটি ও হরমোনাল ইমব্যালান্সের হোমিওপ্যাথিক ব্যবস্থাপনা',
            durationMin: 65,
            isFreePreview: false,
            youtubeVideoId: 'fJ9rUzIMcZQ',
            pdfNotesTitle: 'Adv-Chapter-2-Infertility-Protocol.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf11/view',
          },
          {
            id: 'adv-l4',
            title: '২.২ টিউমার ও ফাইব্রয়েড কেসে মায়াজমেটিক ওষুধ নির্বাচন',
            durationMin: 60,
            isFreePreview: false,
            youtubeVideoId: '3JZ_D3ELwOQ',
            pdfNotesTitle: 'Adv-Chapter-2-Tumor-Management.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf12/view',
          },
        ],
      },
      {
        id: 'adv-c3',
        chapterNo: 3,
        title: 'মর্নিং সাপোর্ট ক্লিনিক্যাল কেস ডিসকাশন সিরিজ',
        description: 'চেম্বারের বাস্তব জটিল রোগীদের কেস প্রেজেন্টেশন ও স্যারের লাইভ প্রেসক্রিপশন',
        lessons: [
          {
            id: 'adv-l5',
            title: '৩.১ কেস স্টাডি ০১: দীর্ঘমেয়াদি চর্মরোগ ও অবদমিত সোরার চিকিৎসা',
            durationMin: 55,
            isFreePreview: false,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Adv-Chapter-3-Skin-Cases.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf13/view',
          },
          {
            id: 'adv-l6',
            title: '৩.২ কেস স্টাডি ০২: জটিল গ্যাস্ট্রো ও লিভার সিরোসিসের হোমিওপ্যাথিক নিয়ন্ত্রণ',
            durationMin: 50,
            isFreePreview: false,
            youtubeVideoId: 'LXb3EKWsInQ',
            pdfNotesTitle: 'Adv-Chapter-3-Liver-Cases.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-pdf14/view',
          },
        ],
      },
    ],
  },
];

export const initialFaqs: FAQItem[] = [
  {
    question: 'আমি নতুন শিক্ষার্থী বা ডিএইচএমএস ছাত্র, আমি কি এই কোর্সে বুঝতে পারব?',
    answer: 'হ্যাঁ, অবশ্যই! কোর্সটি একদম মৌলিক স্তর থেকে শুরু করে ধাপে ধাপে জটিল বিষয়ে নিয়ে যাওয়া হয়। অর্গানন অব মেডিসিনের প্রতিটি নিয়ম ও মেটেরিয়া মেডিকার ওষুধের তুলনামূলক চিত্র এমনভাবে বোঝানো হয় যেন নতুনরাও অত্যন্ত সহজে আত্মস্থ করতে পারেন।',
  },
  {
    question: 'কোর্সের ক্লাসগুলো কীভাবে অনুষ্ঠিত হয়?',
    answer: 'প্রতি সপ্তাহে নির্ধারিত দিনে রাত ৯:৩০ টায় সরাসরি গুগল মিট (Google Meet) এর মাধ্যমে ইন্টারঅ্যাক্টিভ লাইভ ক্লাস অনুষ্ঠিত হয়। এছাড়া প্রতিটি ক্লাসের হাই-কোয়ালিটি রেকর্ডিং এবং লেকচার শিট (PDF) ড্যাশবোর্ডে সারাজীবনের জন্য সংরক্ষিত থাকে।',
  },
  {
    question: 'এডভান্সড ব্যাচের সকালের মর্নিং কেস সাপোর্ট কী?',
    answer: 'এডভান্সড ব্যাচের চিকিৎসকদের জন্য সপ্তাহে ৬ দিন (শনিবার থেকে বৃহস্পতিবার) সকাল ৮:০০ টায় বিশেষ লাইভ কেস সেশন অনুষ্ঠিত হয়। সেখানে চিকিৎসকরা তাদের চেম্বারের জটিল ও গোলমেলে কেস সরাসরি স্যারের সামনে উপস্থাপন করে প্রেসক্রিপশন তৈরি করতে পারেন।',
  },
  {
    question: 'ভর্তি ফি ও মাসিক ফি প্রদানের নিয়ম কী?',
    answer: 'ভর্তি ফি এককালীন ১,০০০/- টাকা দিয়ে রেজিস্ট্রেশন সম্পন্ন করতে হবে। এরপর প্রতি ইংরেজি মাসের ১ থেকে ৩ তারিখের মধ্যে (সর্বোচ্চ ৫ তারিখ) মাত্র ৫০০/- টাকা মাসিক ফি বিকাশ মার্চেন্ট নম্বর 01815-883101 (Payment) অথবা নগদ নম্বরে পরিশোধ করে TrxID ড্যাশবোর্ডে জমা দিতে হবে।',
  },
  {
    question: 'কোর্স শেষে PTF সার্টিফিকেট কীভাবে পাব?',
    answer: '৬ মাসের কোর্স সফলভাবে সম্পন্ন করার পর প্যারামেডিকেল টেকনোলজি ফাউন্ডেশন (PTF) এর গভর্নমেন্ট রেজিস্টার্ড হার্ডকপি সার্টিফিকেট সুন্দরবন বা এসএ পরিবহন কুরিয়ার সার্ভিসের মাধ্যমে সরাসরি আপনার ঠিকানায় হোম ডেলিভারি করা হবে।',
  },
  {
    question: 'অনলাইনে কি রোগী দেখার কোনো ব্যবস্থা আছে?',
    answer: 'না। বিডি হোমিও প্রশিক্ষণ কেন্দ্র শুধুমাত্র চিকিৎসক ও শিক্ষার্থীদের জন্য একটি পিওর অ্যাকাডেমিক প্রশিক্ষণ প্রতিষ্ঠান। এখানে কোনো প্রকার অনলাইন রোগী দেখা হয় না বা চিকিৎসা পরামর্শ দেওয়া হয় না।',
  },
];