import { Course, SiteSettings, FAQItem, TestimonialItem, GalleryItem, VideoShowcaseItem } from './types';

export const initialGalleryImages: GalleryItem[] = [
  {
    id: 'g1',
    src: '/assets/gallery/certificate-ptf-1.jpg',
    title: 'কৃতি শিক্ষার্থীদের PTF সার্টিফিকেট বিতরণী',
    subtitle: 'কোর্স সমাপনী ব্যাচ ও সম্মাননা',
    category: 'সার্টিফিকেশন',
    desc: '৬ মাসের কোর্স সমাপনী সফল শিক্ষার্থীদের মাঝে সনদ ও ক্রেস্ট প্রদান অনুষ্ঠান।',
    date: 'জুলাই ২০২৬',
    showOnHome: true,
  },
  {
    id: 'g2',
    src: '/assets/gallery/workshop-practical.jpg',
    title: 'হোমিওপ্যাথিক কেস স্টাডি ও বাস্তব কর্মশালা',
    subtitle: 'ডাঃ মোঃ গিয়াস উদ্দিন স্যারের সরাসরি ক্লিনিক্যাল ক্লাস',
    category: 'কর্মশালা',
    desc: 'বাস্তব রোগীর কেস টেকিং ও লক্ষণ সংগ্রহের ব্যবহারিক কর্মশালা।',
    date: 'আগস্ট ২০২৬',
    showOnHome: true,
  },
  {
    id: 'g3',
    src: '/assets/gallery/seminar-session.jpg',
    title: 'চিকিৎসকদের সাথে মতবিনিময় ও গ্রুপ স্টাডি',
    subtitle: 'বিভিন্ন জেলা থেকে আগত চিকিৎসকদের অভিজ্ঞতা শেয়ার',
    category: 'আলোচনা সভা',
    desc: 'ক্লিনিক্যাল প্র্যাকটিসের জটিল সমস্যা ও অর্গাননের নীতিমালা প্রয়োগ নিয়ে আলোচনা।',
    date: 'জুন ২০২৬',
    showOnHome: true,
  },
  {
    id: 'g4',
    src: '/assets/gallery/clinical-books.jpg',
    title: 'হ্যানিম্যানের মূলগ্রন্থ ও রেপার্টরি গবেষণা',
    subtitle: 'ক্লাসিক্যাল নীতিমালার প্র্যাকটিক্যাল ব্যবহার',
    category: 'একাডেমিক সেশন',
    desc: 'কেনটের রেপার্টরি ও অর্গানন অব মেডিসিনের সরাসরি রেফারেন্স স্টাডি।',
    date: 'মে ২০২৬',
    showOnHome: true,
  },
  {
    id: 'g5',
    src: '/assets/gallery/ptf-certificate-distribution.jpg',
    title: 'PTF রেজিস্টার্ড প্র্যাকটিশনার সনদ প্রদান',
    subtitle: 'প্যারামেডিকেল টেকনোলজি ফাউন্ডেশন অ্যাপ্রুভড',
    category: 'সার্টিফিকেশন',
    desc: 'সার্টিফিকেটধারী চিকিৎসকদের প্রফেশনাল ক্যারিয়ার সহায়তা প্রদান।',
    date: 'এপ্রিল ২০২৬',
    showOnHome: false,
  },
  {
    id: 'g6',
    src: '/assets/gallery/real-workshop-seminar.jpg',
    title: 'বিশেষ ড্রাগ পিকচার ও মেটেরিয়া মেডিকা সেশন',
    subtitle: 'পলিক্রেস্ট ওষুধের গভীর মনোদৈহিক বিশ্লেষণ',
    category: 'কর্মশালা',
    desc: 'সালফার, লাইকোপোডিয়াম ও নাক্স ভমিকার তুলনামূলক ড্রাগ স্টাডি।',
    date: 'মার্চ ২০২৬',
    showOnHome: false,
  },
  {
    id: 'g7',
    src: '/assets/gallery/student-batch.jpg',
    title: 'নবীন ব্যাচের ওরিয়েন্টেশন ও পরিচিতি সভা',
    subtitle: 'অনলাইন ও অফলাইন শিক্ষার্থীদের মিলনমেলা',
    category: 'আলোচনা সভা',
    desc: 'দেশ ও বিদেশের শিক্ষার্থীদের অংশগ্রহণে প্রাণবন্ত ওরিয়েন্টেশন ক্লাস।',
    date: 'ফেব্রুয়ারি ২০২৬',
    showOnHome: false,
  },
  {
    id: 'g8',
    src: '/assets/gallery/workshop-discussion.jpg',
    title: 'মর্নিং কেস ডিসকাশন ও প্রেসক্রিপশন গাইডলাইন',
    subtitle: 'সরাসরি রোগীর উপসর্গ বিশ্লেষণ',
    category: 'কর্মশালা',
    desc: 'চেম্বারের জটিল ও দুরারোগ্য রোগীদের সঠিক ওষুধ নির্বাচন প্রটোকল।',
    date: 'জানুয়ারি ২০২৬',
    showOnHome: false,
  },
  {
    id: 'g9',
    src: '/assets/gallery/clinical-book-session.jpg',
    title: 'মায়াজমেটিক এনালাইসিস ও ক্লাসিক্যাল থেরাপিউটিক্স',
    subtitle: 'সোরা, সাইকোসিস ও সিফিলিস স্টাডি',
    category: 'একাডেমিক সেশন',
    desc: 'মিশ্র মায়াজম ও ক্রনিক ডিজিজ চিকিৎসার নিয়মতান্ত্রিক পাঠদান।',
    date: 'ডিসেম্বর ২০২৫',
    showOnHome: false,
  },
];

export const initialVideoShowcase: VideoShowcaseItem[] = [
  {
    id: 'v1',
    title: 'সালফার (Sulphur) এর লক্ষণ ও গভীর মনোদৈহিক বিশ্লেষণ',
    subtitle: 'হ্যানিম্যানের অর্গানন ও মেটেরিয়া মেডিকার আলোকে কিং অব অ্যান্টিসোরিক ড্রাগ স্টাডি',
    youtubeId: '3JZ_D3ELwOQ',
    duration: '১৮:৪৫ মিনিট',
    tag: 'মেটেরিয়া মেডিকা',
  },
  {
    id: 'v2',
    title: 'হোমিও রেপার্টরি শিক্ষা — মাত্র ৩/৪ মাসে গভীর জ্ঞান অর্জন',
    subtitle: 'কেনটের প্রধান রুব্রিক্স শনাক্তকরণ ও রেপার্টরাইজেশন কৌশল',
    youtubeId: 'M7lc1UVf-VE',
    duration: '২২:৩০ মিনিট',
    tag: 'রেপার্টরি মাস্টারি',
  },
  {
    id: 'v3',
    title: 'নাক্স ভমিকা (Nux Vomica) — প্রভিউ স্টাডি উইথ স্যার',
    subtitle: 'দৈনন্দিন প্র্যাকটিসে ধাতুগুন অনুযায়ী সঠিক লক্ষণ নির্বাচন',
    youtubeId: 'LXb3EKWsInQ',
    duration: '১৫:২০ মিনিট',
    tag: 'ক্লিনিক্যাল স্টাডি',
  },
  {
    id: 'v4',
    title: 'বন্ধ্যাত্ব ও জরায়ু টিউমারের সফল হোমিওপ্যাথিক ব্যবস্থাপনা',
    subtitle: 'সফলতার সাথে প্র্যাকটিক্যাল কেস স্টাডি ও ফলাফল আলোচনা',
    youtubeId: 'fJ9rUzIMcZQ',
    duration: '২৫:১০ মিনিট',
    tag: 'কেস অ্যানালাইসিস',
  },
];

export const initialTestimonials: TestimonialItem[] = [
  {
    id: 't1',
    name: 'ডাঃ মোঃ রফিকুল ইসলাম',
    designation: 'হোমিও প্র্যাকটিশনার, বগুড়া সদর',
    batchName: 'বেসিক ফাউন্ডেশন ৯ম ব্যাচ',
    quote: 'ডিএইচএমএস শেষ করার পরও চেম্বারে রোগী দেখে ওষুধ নির্বাচনে দ্বিধায় ভুগতাম। ডাঃ মোঃ গিয়াস উদ্দিন স্যারের অর্গানন ও মেটেরিয়া মেডিকার বিশ্লেষণ আমার চেম্বার প্র্যাকটিসে শতভাগ আত্মবিশ্বাস ফিরিয়ে দিয়েছে।',
    rating: 5,
  },
  {
    id: 't2',
    name: 'ডাঃ ফারহানা আক্তার',
    designation: 'ডিএইচএমএস শেষ বর্ষ, খুলনা',
    batchName: 'এডভান্সড ক্লিনিক্যাল ব্যাচ',
    quote: 'স্যারের সকালের মর্নিং কেস সাপোর্ট আমার জন্য আশীর্বাদস্বরূপ। প্রতিদিন সকালে চেম্বারের বাস্তব রোগীদের কেস নিয়ে স্যারের সাথে সরাসরি কথা বলে সিমিলিমাম ওষুধ নির্ধারণ করতে পারছি।',
    rating: 5,
  },
  {
    id: 't3',
    name: 'ডাঃ কামরুল হাসান',
    designation: 'রেজিস্টার্ড ক্লাসিক্যাল চিকিৎসক, চট্টগ্রাম',
    batchName: 'বেসিক ফাউন্ডেশন ৮ম ব্যাচ',
    quote: 'রেপার্টরির এমন সহজ ও প্রাঞ্জল ব্যাখ্যা আগে কোথাও পাইনি। ক্লাসিক্যাল নীতিমালার প্র্যাকটিক্যাল প্রয়োগ ও PTF অনুমোদিত সার্টিফিকেট আমার চিকিৎসাজীবনের বড় অর্জন।',
    rating: 5,
  },
];

export const initialSiteSettings: SiteSettings = {
  siteTitle: 'বিডি হোমিও প্রশিক্ষণ কেন্দ্র',
  slogan: 'Right Homeopath, Right Homeopathy',
  heroHeadline: 'হোমিওপ্যাথির খাঁটি দর্শনে আত্মবিশ্বাসী প্র্যাকটিশনার হওয়ার ৬ মাসের মাস্টার একাডেমি',
  heroSubheadline: 'ডাঃ মোঃ গিয়াস উদ্দিন স্যারের সরাসরি নির্দেশনায় অর্গানন অব মেডিসিন, মেটেরিয়া মেডিকা ও রেপার্টরি ভিত্তিক সপ্তাহে ২টি লাইভ ক্লাস ও ৬ দিন মর্নিং কেস সাপোর্ট।',
  doctorName: 'ডাঃ মোঃ গিয়াস উদ্দিন',
  doctorTitle: 'প্রতিষ্ঠাতা ও প্রধান প্রশিক্ষক, বিডি হোমিও একাডেমি',
  doctorDegrees: 'ডিএইচএমএস (ঢাকা), বিএইচএমএস (রিসার্চার), ক্লাসিক্যাল অর্গানন গবেষক',
  doctorExperience: '২০+ বছরের অভিজ্ঞ প্র্যাকটিশনার ও ট্রেইনার',
  doctorChamberTime: 'শনিবার থেকে বৃহস্পতিবার (সকাল ৯:০০ - রাত ৮:০০)',
  doctorMessage: 'অর্গাননের সঠিক জ্ঞান ছাড়া লক্ষণ ভিত্তিক হোমিওপ্যাথি চিকিৎসা অসম্ভব। আমাদের লক্ষ্য— প্রতিটি শিক্ষার্থী যেন কেবল তাত্ত্বিক জ্ঞান নয়, বরং চেম্বারে রোগী আরোগ্যের পূর্ণ আত্মবিশ্বাস নিয়ে চিকিৎসা সেবা প্রদান করতে পারেন।',
  heroImageUrl: '/assets/sir/sir-hero.jpg',
  doctorPortraitUrl: '/assets/sir/sir-portrait.jpg',
  ptfCertificateImageUrl: '/assets/gallery/certificate-ptf-1.jpg',
  metaOgImageUrl: 'https://bdhomeo.com/assets/sir/sir-hero.jpg',
  galleryImages: initialGalleryImages,
  videoShowcaseList: initialVideoShowcase,
  testimonials: initialTestimonials,
  bkashNumber: '01815-883101',
  bkashType: 'Merchant',
  nagadNumber: '01811-123993',
  nagadType: 'Personal',
  rocketNumber: '01815-883101',
  whatsappNumber: '01811-123993',
  helplineNumber: '01811-123993',
  alternateHelpline: '01815-883101',
  officialEmail: 'bdhomeo@gmail.com',
  chamberAddress: 'ঢাকা, বাংলাদেশ',
  classTime: 'রাত ৯:৩০ টা',
  morningSupportTime: 'সকাল ৮:০০ টা',
  googleMeetUrl: 'https://meet.google.com/bdhomeo-live-class',
  noticeText: 'আগামী নতুন ব্যাচের ভর্তি চলছে! ফ্রি ওরিয়েন্টেশন ক্লাসে অংশ নিতে এখনই রেজিস্ট্রেশন করুন। হেল্পলাইন: 01811-123993',
  youtubeUrl: 'https://www.youtube.com/@bdhomeo/videos',
  facebookUrl: 'https://www.facebook.com/geaus.uddin.81099',
  facebookGroupUrl: 'https://www.facebook.com/groups/bdhomeo',
  telegramUrl: 'https://t.me/bdhomeo',
};

export const initialCourses: Course[] = [
  {
    id: 'course-basic-foundation',
    slug: 'basic-homeopathy-foundation',
    title: 'বেসিক হোমিওপ্যাথি ফাউন্ডেশন কোর্স',
    subtitle: 'হ্যানিম্যানের অর্গানন, মেটেরিয়া মেডিকা ও রেপার্টরি পরিচিতির ৬ মাসের পূর্ণাঙ্গ একাডেমিক কোর্স',
    batchType: 'basic',
    durationMonths: 6,
    admissionFee: 1000,
    monthlyFee: 500,
    liveSchedule: 'সপ্তাহে ২ দিন লাইভ ক্লাস (রাত ৯:৩০)',
    morningSupport: 'সপ্তাহে ৬ দিন সকাল ৮:০০ টায় লাইভ মর্নিং কেস সাপোর্ট',
    thumbnailUrl: '/assets/courses/basic-batch.jpg',
    description: 'এই কোর্সের মাধ্যমে আপনি হোমিওপ্যাথির মৌলিক দর্শন, ভাইটাল ফোর্স তত্ত্ব, পলিক্রেস্ট ওষুধের ড্রাগ পিকচার এবং বাস্তব কেস টেকিংয়ের নিখুঁত কৌশল শিখবেন।',
    features: [
      'সাপ্তাহিক ২টি গুগল মিট লাইভ ক্লাস (রাত ৯:৩০)',
      'সপ্তাহে ৬ দিন সকাল ৮টায় সরাসরি প্র্যাকটিক্যাল কেস ডিসকাশন',
      'অধ্যায়ভিত্তিক সাজানো ও কালারফুল PDF লেকচার শিট',
      'PTF অনুমোদিত প্রফেশনাল সার্টিফিকেট (কুরিয়ার হোম ডেলিভারি)',
      'লাইফটাইম রেকর্ডেড ক্লাস লাইব্রেরি অ্যাক্সেস',
    ],
    curriculum: [
      {
        id: 'c1',
        chapterNo: 1,
        title: 'অধ্যায় ১: অর্গানন অব মেডিসিন — মৌলিক ভিত্তি ও দর্শন',
        description: 'হ্যানিম্যানের মূল এফোরিজম ও হোমিওপ্যাথিক নীতিমালার গভীর বিশ্লেষণ',
        lessons: [
          {
            id: 'l1',
            title: '১.১ পরিচিতি ও অর্গাননের মূল দর্শন (ফ্রি ওরিয়েন্টেশন ক্লাস)',
            durationMin: 45,
            isFreePreview: true,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Organon_Chapter_1_Handout.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-organon-1/view',
            notesContent: 'এই ক্লাসে অর্গানন অব মেডিসিনের ১ম থেকে ৮ম এফোরিজমের মূল তাৎপর্য ব্যাখ্যা করা হয়েছে। চিকিৎসকের একমাত্র ও সর্বোচ্চ লক্ষ্য হল পীড়িত ব্যক্তিকে দ্রুত, মৃদু ও স্থায়ীভাবে আরোগ্য করা। ভাইটাল ফোর্স ও লক্ষণ সংগ্রহের গুরুত্ব আলোচনা করা হয়েছে।',
          },
          {
            id: 'l2',
            title: '১.২ ভাইটাল ফোর্স ও ডিজিজ ডাইনামিক্স (এফোরিজম ৯-১৭)',
            durationMin: 55,
            isFreePreview: false,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Vital_Force_Summary.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-vital-force/view',
            notesContent: 'প্রাণশক্তি (Vital Force) কীভাবে মানবদেহকে সুশৃঙ্খলভাবে সচল রাখে এবং রোগাক্রান্ত হলে লক্ষণ প্রকাশ করে তা বিস্তারিত বুঝানো হয়েছে। এফোরিজম ৯-১৭ এর ক্লিনিক্যাল অ্যাপ্লিকেশন।',
          },
          {
            id: 'l3',
            title: '১.৩ মায়াজম পরিচিতি: সোরা, সাইকোসিস ও সিফিলিস',
            durationMin: 60,
            isFreePreview: false,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Miasm_Foundation.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-miasm/view',
            notesContent: 'হ্যানিম্যানের ক্রনিক ডিজিজের মায়াজমেটিক তত্ত্ব। সোরা (Psora), সাইকোসিস (Sycosis) ও সিফিলিস (Syphilis) এর স্বতন্ত্র লক্ষণ এবং মিশ্র মায়াজম শনাক্ত করার কৌশল।',
          },
        ],
      },
      {
        id: 'c2',
        chapterNo: 2,
        title: 'অধ্যায় ২: ক্লিনিক্যাল মেটেরিয়া মেডিকা — পলিক্রেস্ট ড্রাগ স্টাডি',
        description: 'গুরুত্বপূর্ণ হোমিওপ্যাথিক ওষুধের মনোদৈহিক লক্ষণ ও তুলনামূলক বিশ্লেষণ',
        lessons: [
          {
            id: 'l4',
            title: '২.১ সালফার (Sulphur) এর সার্বদৈহিক ও মানসিক ড্রাগ পিকচার',
            durationMin: 50,
            isFreePreview: false,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Sulphur_Drug_Picture.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-sulphur/view',
            notesContent: 'কিং অব অ্যান্টিসোরিক ওষুধ সালফারের থার্মাল রিলেশন (হট পেসেন্ট), নোংরা স্বভাব অথচ দার্শনিক মন, সকাল ১১টায় ক্ষুধার অনুভূতি ও ত্বকের চুলকানির সামগ্রিক রূপ।',
          },
          {
            id: 'l5',
            title: '২.২ নাক্স ভমিকা (Nux Vomica) ও লাইকোপোডিয়াম ড্রাগ স্টাডি',
            durationMin: 52,
            isFreePreview: false,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Nux_Lyc_Comparison.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-nux-lyc/view',
            notesContent: 'অতিরিক্ত মানসিক পরিশ্রম, সেডেন্টারি লাইফস্টাইল ও গ্যাস্ট্রিকের রোগীদের ক্ষেত্রে নাক্স ভমিকা বনাম লাইকোপোডিয়ামের তুলনামূলক লক্ষণ স্টাডি।',
          },
        ],
      },
      {
        id: 'c3',
        chapterNo: 3,
        title: 'অধ্যায় ৩: কেস টেকিং ও লক্ষণ সংগ্রহ পদ্ধতি',
        description: 'বাস্তব চেম্বারে রোগীর কেস হিস্ট্রি রেকর্ডিং ও মায়াজমেটিক মূল্যায়ন',
        lessons: [
          {
            id: 'l6',
            title: '৩.১ স্ট্যান্ডার্ড হোমিওপ্যাথিক কেস হিস্ট্রি ফরম্যাট ও প্রশ্নমালা',
            durationMin: 48,
            isFreePreview: false,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Case_Taking_Format_Sheet.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-case-taking/view',
            notesContent: 'রোগীর প্রধান কষ্ট (Chief Complaint), অতীত রোগ ইতিহাস, পারিবারিক ইতিহাস, মানসিক অনুভূতি ও মোডালিটিজ (হ্রাস-বৃদ্ধি) সুশৃঙ্খলভাবে রেকর্ড করার গাইড।',
          },
        ],
      },
    ],
  },
  {
    id: 'course-advance-clinical',
    slug: 'advanced-clinical-repertory',
    title: 'এডভান্সড ক্লিনিক্যাল রেপার্টরি ও কেস ম্যানেজমেন্ট',
    subtitle: 'জটিল ও ক্রনিক রোগের সমাধান, রেপার্টরাইজেশন এবং সপ্তাহে ৬ দিন সকালের বিশেষ মর্নিং কেস সাপোর্ট',
    batchType: 'advance',
    durationMonths: 6,
    admissionFee: 1000,
    monthlyFee: 500,
    liveSchedule: 'সপ্তাহে ২ দিন লাইভ ক্লাস (রাত ৯:৩০)',
    morningSupport: 'সপ্তাহে ৬ দিন সকাল ৮:০০ টায় লাইভ মর্নিং কেস সাপোর্ট',
    thumbnailUrl: '/assets/courses/advance-batch.jpg',
    description: 'ক্রনিক ডিজিজ, অটোইমিউন রোগ এবং দুরারোগ্য রোগীদের সঠিক সিমিলিমাম ওষুধ নির্ধারণ ও পটেন্সি সিলেকশনের গভীর ক্লিনিক্যাল প্রশিক্ষণ।',
    features: [
      'সাপ্তাহিক ২টি এডভান্সড ক্লিনিক্যাল ক্লাস',
      'সপ্তাহে ৬ দিন মর্নিং চেম্বার লাইভ কেস সলভিং',
      'কেন্ট ও সিন্থেসিস রেপার্টরির রুব্রিক্স ডিকোডিং',
      'PTF অনুমোদিত এডভান্সড প্র্যাকটিশনার সার্টিফিকেট',
      'অফিসিয়াল হোয়াটসঅ্যাপ ভিআইপি ডক্টরস গ্রুপ অ্যাক্সেস',
    ],
    curriculum: [
      {
        id: 'adv-c1',
        chapterNo: 1,
        title: 'অধ্যায় ১: রেপার্টরি মাস্টারি ও রুব্রিক্স ডিকোড',
        description: 'লক্ষণ থেকে রেপার্টরির সঠিক রুব্রিক্সে রূপান্তরের ব্যবহারিক নিয়ম',
        lessons: [
          {
            id: 'adv-l1',
            title: '১.১ কেনটের রেপার্টরি মাইন্ড সেকশন ও ক্লিনিক্যাল ব্যবহার (ফ্রি ক্লাস)',
            durationMin: 50,
            isFreePreview: true,
            youtubeVideoId: 'M7lc1UVf-VE',
            pdfNotesTitle: 'Kent_Mind_Rubrics_Guide.pdf',
            pdfNotesUrl: 'https://drive.google.com/file/d/sample-kent/view',
            notesContent: 'কেনটের রেপার্টরির মাইন্ড চ্যাপ্টারের গুরুত্বপূর্ণ রুব্রিক্স যেমন: Fear, Delusion, Anxiety, Irritability ইত্যাদি বাস্তব রোগীর মুখের ভাষার সাথে মিলিয়ে বের করার ক্লিনিক্যাল নিয়ম।',
          },
        ],
      },
    ],
  },
];

export const initialFaqs: FAQItem[] = [
  {
    question: 'কোর্সের ক্লাসগুলো কীভাবে অনুষ্ঠিত হবে?',
    answer: 'সকল ক্লাস সরাসরি গুগল মিট (Google Meet)-এর মাধ্যমে লাইভ অনুষ্ঠিত হবে। প্রতি ক্লাসের আগে গ্রুপে ও ড্যাশবোর্ডে মিট লিংক শেয়ার করা হয়। ক্লাস মিস হলে সম্পূর্ণ ক্লাসরুম থেকে ফুল HD রেকর্ডেড ভিডিও লেকচার দেখার সুযোগ রয়েছে।',
  },
  {
    question: 'ভর্তি ফি ও মাসিক ফি প্রদানের নিয়ম কী?',
    answer: 'এককালীন ভর্তি ফি ১,০০০/- টাকা দিয়ে রেজিস্ট্রেশন সম্পন্ন করতে হবে। এরপর প্রতি ইংরেজি মাসের ১-৩ তারিখের মধ্যে মাসিক ফি ৫০০/- টাকা বিকাশ মার্চেন্ট (01815-883101 Payment অপশন) অথবা নগদে পরিশোধ করে ড্যাশবোর্ডে TrxID সাবমিট করতে হবে।',
  },
  {
    question: 'PTF সার্টিফিকেট কীভাবে দেওয়া হয়?',
    answer: '৬ মাসের কোর্স সমাপনী সফলভাবে সম্পন্ন করার পর প্যারামেডিকেল টেকনোলজি ফাউন্ডেশন (PTF) অনুমোদিত অফিসিয়াল সার্টিফিকেট সুন্দরবন কুরিয়ার সার্ভিসের মাধ্যমে সরাসরি আপনার ঠিকানায় হোম ডেলিভারি করা হবে।',
  },
  {
    question: 'সকালের মর্নিং কেস সাপোর্ট কী?',
    answer: 'প্রতি সপ্তাহে ৬ দিন সকাল ৮:০০ টায় সরাসরি ডাঃ মোঃ গিয়াস উদ্দিন স্যারের পরিচালনায় চেম্বারের জটিল ও নতুন রোগীর প্রেসক্রিপশন এবং ড্রাগ সিলেকশনের সরাসরি লাইভ সাপোর্ট দেওয়া হয়।',
  },
];
